SELECT (SELECT G.VL_PRMT_GRAL FROM TSGF_PRMT_GRAL_DTHE G WHERE G.DS_PRMT_GRAL = 'NomeResp' and G.DT_TRNI_VGCA_PRMT_GRAL_DTHE is null) AS nomeContato ,
	   nvl((SELECT G.VL_PRMT_GRAL FROM TSGF_PRMT_GRAL_DTHE G WHERE G.DS_PRMT_GRAL = 'TelResp' and G.DT_TRNI_VGCA_PRMT_GRAL_DTHE is null),'00-00000000') AS telefoneContato ,
       (SELECT G.VL_PRMT_GRAL FROM TSGF_PRMT_GRAL_DTHE G WHERE G.DS_PRMT_GRAL = 'Bacen_CNPJ' and G.DT_TRNI_VGCA_PRMT_GRAL_DTHE is null) AS Cnpj
  FROM DUAL